server:
  port: 8089

spring:
  application:
    name: ms-cotizador
  datasource:
    url: jdbc:mysql://localhost:3306/db_cotizaciones?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

cliente:
  service:
    url: localhost:8080